version: '0.6.1'
description: 'The backend app is the official app to develop, configure and maintain your API.'
screenshot: 'https://raw.githubusercontent.com/apioo/fusio/master/doc/_static/backend.png'
website: 'https://github.com/apioo/fusio-backend'
downloadUrl: 'https://www.fusio-project.org/files/fusio.zip'
sha1Hash: 'de93335ba3b8f5b171aff8214249b5bcbf796a2b'
