version: '0.6.1'
description: 'The backend app is the official app to develop, configure and maintain your API.'
screenshot: 'https://raw.githubusercontent.com/apioo/fusio/master/doc/_static/backend.png'
website: 'https://github.com/apioo/fusio-backend'
downloadUrl: 'https://codeload.github.com/chay22/dev-fusio-backend/legacy.zip/release'
sha1Hash: '95ec0001a3e6db14cb67c00c0812b6bd81cbdabb'
