version: '0.6.1'
description: 'The backend app is the official app to develop, configure and maintain your API.'
screenshot: 'https://raw.githubusercontent.com/apioo/fusio/master/doc/_static/backend.png'
website: 'https://github.com/apioo/fusio-backend'
downloadUrl: 'https://codeload.github.com/chay22/dev-fusio-backend/legacy.zip/src-release'
sha1Hash: '90f0ed7742876a81c08c6c0728ba5bda257e5786'
